sudo: false
language: php

php:
    - 7.2
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

install:
    - composer self-update
    - composer install

script:
    - phpdbg -qrr vendor/bin/phpunit --configuration . --coverage-text